apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-compute
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-compute:v0.38.1
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: custom-gcp-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  serviceAccountName: crossplane
  args:
    - --poll=10m
    - -d
    - --provider-ttl=300
