apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-resources
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
      include: '*.yaml'
    repoURL: https://github.com/elvis-cai/xplane-code.git
    targetRevision: HEAD
    path: cloud-resources
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
